# Numpy

In [1]:
# !pip install numpy

In [2]:
import numpy

In [3]:
vector = [1, 2, 3]

In [4]:
print(type(vector))

<class 'list'>


In [5]:
nvector = numpy.array(vector)

In [6]:
# The N-dimensional array (ndarray)
# https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

print(type(nvector))

<class 'numpy.ndarray'>


In [7]:
nvector.shape

(3,)

In [8]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(type(matrix))

<class 'list'>


In [9]:
nmatrix = numpy.array(matrix)

print(type(nmatrix))

<class 'numpy.ndarray'>


In [10]:
nmatrix.shape

(3, 3)

##### https://tensorflownet.readthedocs.io/en/latest/Tensor.html
<center>
    <img src="https://tensorflownet.readthedocs.io/en/latest/_static/tensor-naming.png" width="800" alt="Scalars, Vectors, Matrices and Tensors with Tensorflow 2.0 logo"  />
</center>

<center>
    <img src="https://www.researchgate.net/profile/Kim-Batselier/publication/310823791/figure/fig2/AS:443479336722433@1482745121813/An-example-tensor-A-R-432.png" width="250">
</center>

In [11]:
# SCALAR
i = 11

# Row Vector (shape 1×3)
j = [5, 3, 7]

# Column Vector (shape 3×1)
k = [
    5,
    1.5,
    2
]

# MATRIX
l = [
    [4, 19, 8],
    [16, 3, 15]
]

# TENSOR
x = [
    [[1, 2, 3], ['a', 'b', 'c'], ['A', 'B', 'C']],
    [[4, 5, 6], ['d', 'e', 'f'], ['D', 'E', 'F']],
    [[7, 8, 9], ['g', 'h', 'i'], ['G', 'H', 'I']]
]

print(type(x))

<class 'list'>


In [12]:
# https://docs.python.org/3/tutorial/datastructures.html
print('Python List Data Type (Data Structure)')
array = [1, 2, 3]
print(type(array))
print(array)
array

Python List Data Type (Data Structure)
<class 'list'>
[1, 2, 3]


[1, 2, 3]

In [13]:
# https://numpy.org/doc/stable/reference/arrays.ndarray.html
narr = numpy.array(array)
print('The N-dimensional array (ndarray)')
print(type(narr))
print(narr)
narr

The N-dimensional array (ndarray)
<class 'numpy.ndarray'>
[1 2 3]


array([1, 2, 3])

In [14]:
numpy.resize(narr, (4, 4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [15]:
numpy.resize(narr, (3, 1))

array([[1],
       [2],
       [3]])

In [16]:
numpy.resize(narr, (2, 1))

array([[1],
       [2]])

In [17]:
# narr.resize((3, 3))

# OUTPUT ---->
'''
ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False
'''
#        <----

# refcheck: bool, optional
# If refcheck=False, reference count will not be checked. Default is True.
# https://numpy.org/doc/stable/reference/generated/numpy.ndarray.resize.html

narr.resize((3, 3), refcheck=False)

In [18]:
print(type(narr))
print()
print(narr)
print()
narr

<class 'numpy.ndarray'>

[[1 2 3]
 [0 0 0]
 [0 0 0]]



array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
matrix = numpy.ones((4, 5))

print(matrix)
print()

print(matrix[0][3])
print(type(matrix[0][3]))
print()

matrix

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

1.0
<class 'numpy.float64'>



array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
matrix = numpy.zeros((4, 5))

print(matrix)
print()

print(matrix[0][4])
print(type(matrix[0][4]))
print()

matrix

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

0.0
<class 'numpy.float64'>



array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
print(narr)
print()

# diagonal ---> خط مورب یا قطر
# Extract a diagonal or construct a diagonal array.
# https://numpy.org/doc/stable/reference/generated/numpy.diag.html
numpy.diag(narr)

[[1 2 3]
 [0 0 0]
 [0 0 0]]



array([1, 0, 0])

In [22]:
numpy.repeat([4, 3, 2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [23]:
numpy.repeat(numpy.array([4, 3, 2]), 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [24]:
# Any type of data can be placed inside a Python list.
pylist = [1, 1.5, 'number', True]

pylist

[1, 1.5, 'number', True]

In [25]:
# Inside numpy, it is better that all members are of the same data type. Because it speeds up the processes.
narray = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

print(numpy.diag(narray))
print()

print(type(narray))
narray

[ 1  6 11 16]

<class 'numpy.ndarray'>


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
narray = numpy.array([ [1, 1.5, 'number', True], [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] ])

print(numpy.diag(narray))
print()

print(type(narray))
print()

narray

['1' '2' '7' '12']

<class 'numpy.ndarray'>



array([['1', '1.5', 'number', 'True'],
       ['1', '2', '3', '4'],
       ['5', '6', '7', '8'],
       ['9', '10', '11', '12']], dtype='<U32')

In [27]:
m1 = numpy.ones((4, 5), int)
print(type(m1[0][3]))
m1

<class 'numpy.int32'>


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [28]:
m2 = numpy.zeros((4, 5), int)
print(type(m1[0][3]))
m2

<class 'numpy.int32'>


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

<!-- https://stackoverflow.com/questions/33356442/when-should-i-use-hstack-vstack-vs-append-vs-concatenate-vs-column-stack -->
<center>
    <a href="https://stackoverflow.com/questions/33356442/when-should-i-use-hstack-vstack-vs-append-vs-concatenate-vs-column-stack">
        when-should-i-use-hstack-vstack-vs-append-vs-concatenate-vs-column-stack
    </a>
    <!-- <img src="https://i.sstatic.net/hSM5G.png" width="800" alt=""  /> -->
    <!-- <img src="https://i.sstatic.net/1QBr4.png" width="800" alt=""  /> -->
    <!-- <img src="https://i.sstatic.net/dSZuK.png" width="800" alt=""  /> -->
</center>

In [29]:
# https://numpy.org/doc/stable/reference/generated/numpy.vstack.html
# Stack arrays in sequence vertically (row wise).
numpy.vstack([m1, m2])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [30]:
# https://numpy.org/doc/stable/reference/generated/numpy.hstack.html
# Stack arrays in sequence horizontally (column wise).
numpy.hstack([m1, m2])

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])

###### [1, 2, 3] * [4, 5, 6]

###### ---------------------------------------------------------------------------
###### TypeError                                 Traceback (most recent call last)
###### Cell In[66], line 1
###### ----> 1 [1, 2, 3] * [4, 5, 6]

###### TypeError: can't multiply sequence by non-int of type 'list'

In [31]:
x = numpy.array([1, 2, 3])
y = numpy.array([4, 5, 6])

In [32]:
# Linear Algebra!
z = x * y
z

array([ 4, 10, 18])

In [33]:
x ** 2

array([1, 4, 9])

In [34]:
# https://numpy.org/doc/stable/reference/generated/numpy.dot.html
# Dot product of two arrays. Specifically,

x.dot(y)
# (1*4) + (2*5) + (3*6) ----> 4 + 10 + 18 = 32

32

In [35]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
# https://numpy.org/doc/stable/reference/generated/numpy.ndarray.T.html
# View of the transposed array.

narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [37]:
# https://numpy.org/doc/stable/reference/generated/numpy.transpose.html
# Returns an array with axes transposed.

narr.transpose()

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [38]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [39]:
narr.sum()

6

In [40]:
narr.max()

3

In [41]:
narr.min()

0

In [42]:
# Returns the index of the largest element
narr.argmax()

2

In [43]:
# Returns the index of the smallest element
narr.argmin()

3

In [44]:
narr.mean()

0.6666666666666666

In [45]:
narr.std()

1.0540925533894598

In [46]:
mr = numpy.arange(15)
mr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
mr = numpy.arange(15) ** 2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [48]:
# [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

mr[-6:14:2]
# array([81, 121, 169])

array([ 81, 121, 169])

In [49]:
# [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

mr[5:-1:-1]
# array([])

array([], dtype=int32)

In [50]:
mr[2]

4

In [51]:
mr[1:5]

array([ 1,  4,  9, 16])

In [52]:
mr[1:5:1]

array([ 1,  4,  9, 16])

In [53]:
mr[4:0:-1]

array([16,  9,  4,  1])

In [54]:
mr[:5]

array([ 0,  1,  4,  9, 16])

In [55]:
mr[-2:]

array([169, 196])

In [56]:
# [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

mr[5:12:3]
# array([25, 64, 121])

array([ 25,  64, 121])

In [57]:
# [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

mr[10::2]
#  100 --> END (On The Right)
# array([100, 144, 196])

array([100, 144, 196])

In [58]:
# [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

mr[10::-2]
#  100 --> END (On The Left)
# array([100, 64, 36, 16, 4, 0])

array([100,  64,  36,  16,   4,   0])

In [59]:
# [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

mr[-10::-2]
#   25 --> END (On The Left)
# array([25, 9, 1])

array([25,  9,  1])

In [60]:
# [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

mr[-10:-2:-2]
#   25 --> 169
# array([])

array([], dtype=int32)

In [61]:
mr[-10:-2:2]
# 25, 49, 81, 121

array([ 25,  49,  81, 121])

In [62]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [63]:
numpy.array([
    [1, 2, 3],
    [0, 0, 0],
    [0, 0, 0]
])

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [64]:
narr = numpy.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [65]:
narr[0, 2]

30

In [66]:
narr[0, 2:]

array([30])

In [67]:
narr[0]

array([10, 20, 30])

In [68]:
narr[0,  ]

array([10, 20, 30])

In [69]:
narr[0, :]

array([10, 20, 30])

In [70]:
narr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [71]:
narr[1:, 2]

array([60, 90])

In [72]:
narr[1:, 2:]

array([[60],
       [90]])

In [73]:
narr[:2, 1:]

array([[20, 30],
       [50, 60]])

In [74]:
narr[0:2, 1:]

array([[20, 30],
       [50, 60]])

In [75]:
narr[0:2, 1:3]

array([[20, 30],
       [50, 60]])

In [76]:
# narr[rows  ,  columns]
# Before comma     :  zero dimension       (columns) axis 0  --->  0:2
# After the comma  :  the first dimension  (rows)    axis 1  --->  1:1000
narr[0:2, 1:1000]

array([[20, 30],
       [50, 60]])

In [77]:
narr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [78]:
narr[::2, -1]

array([30, 90])

In [79]:
narr[::2, -1:]

array([[30],
       [90]])

In [80]:
narr[::-1, 2]

array([90, 60, 30])

In [81]:
narr[::-1, 2:]

array([[90],
       [60],
       [30]])

In [82]:
narr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [83]:
narr[-2::, 1:3]

array([[50, 60],
       [80, 90]])

In [84]:
narr[-2::1, 1:3]

array([[50, 60],
       [80, 90]])

In [85]:
narr[narr >= 0]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [86]:
narr[narr >= 70]

array([70, 80, 90])

In [87]:
narr >= 2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [88]:
narr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [89]:
marr = narr[-1]
marr

array([70, 80, 90])

In [90]:
marr[:] = 1
marr

array([1, 1, 1])

In [91]:
marr[:2] = 2
marr

array([2, 2, 1])

In [92]:
narr

array([[10, 20, 30],
       [40, 50, 60],
       [ 2,  2,  1]])

In [93]:
marr = narr.copy()
marr

array([[10, 20, 30],
       [40, 50, 60],
       [ 2,  2,  1]])

In [94]:
marr[:] = 0
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [95]:
narr

array([[10, 20, 30],
       [40, 50, 60],
       [ 2,  2,  1]])

In [96]:
tarr = numpy.random.randint(0, 10, (4, 3))
tarr

array([[9, 4, 3],
       [2, 5, 9],
       [3, 5, 5],
       [5, 7, 1]])

In [97]:
tarr[3, 2]

1

In [98]:
tarr[3:, 2]

array([1])

In [99]:
tarr[3, 2:]

array([1])

In [100]:
tarr[3:, 2:]

array([[1]])

In [101]:
tarr[3::3, 4:1:-2]

array([[1]])

In [102]:
tarr

array([[9, 4, 3],
       [2, 5, 9],
       [3, 5, 5],
       [5, 7, 1]])

In [103]:
for row in tarr:
    # print(row)
    row = row **2
    print(row)

[81 16  9]
[ 4 25 81]
[ 9 25 25]
[25 49  1]


In [104]:
for index, row in enumerate(tarr):
    # print(f'index({index}) is {row}')
    # print('index(' + str(index) + ') is ' + str(row))
    print('index(' + str(index) + ') is ', row)

index(0) is  [9 4 3]
index(1) is  [2 5 9]
index(2) is  [3 5 5]
index(3) is  [5 7 1]


In [105]:
narr

array([[10, 20, 30],
       [40, 50, 60],
       [ 2,  2,  1]])

In [106]:
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [107]:
list(zip(narr, marr))

[(array([10, 20, 30]), array([0, 0, 0])),
 (array([40, 50, 60]), array([0, 0, 0])),
 (array([2, 2, 1]), array([0, 0, 0]))]

In [108]:
numpy.hstack((narr, marr))

array([[10, 20, 30,  0,  0,  0],
       [40, 50, 60,  0,  0,  0],
       [ 2,  2,  1,  0,  0,  0]])

In [109]:
arr = [1, 4, 2, 9, 8, 6, 3]
arr = numpy.array(arr)
arr

array([1, 4, 2, 9, 8, 6, 3])

In [110]:
len(arr) // 2

3

In [111]:
middle = arr[len(arr) // 2]
middle

9

In [112]:
s = smaller_than_the_middle = [x for x in arr if x < middle]
smaller_than_the_middle

[1, 4, 2, 8, 6, 3]

In [113]:
e = equal_than_the_middle = [x for x in arr if x == middle]
equal_than_the_middle

[9]

In [114]:
b = bigger_than_the_middle = [x for x in arr if x > middle]
bigger_than_the_middle

[]

In [115]:
s + b + e

[1, 4, 2, 8, 6, 3, 9]

In [116]:
[1, 4, 2, 8, 6, 3] + [9] + []

[1, 4, 2, 8, 6, 3, 9]

In [117]:
# Data Structures
# Recursive programming

# Algorithm Design

# Recursive Functions
def quicksort(_array_):
    if len(_array_) <= 1:
        return _array_
    
    _array_ = numpy.array(_array_)
    middle = _array_[len(_array_) // 2]
    print('middle:', middle)
    # s --> smaller_than_the_middle
    s = [x for x in _array_ if x < middle]
    print('s:', s)
    # e --> equal_than_the_middle
    e = [x for x in _array_ if x == middle]
    print('e:', e)
    # b --> bigger_than_the_middle
    b = [x for x in _array_ if x > middle]
    print('b:', b)
    print(s, e, b)
    print()

    return quicksort(s) + e + quicksort(b)

In [118]:
pylist = [3, 6, 4 ,1, 3, 9, 4]
quicksort(pylist)

middle: 1
s: []
e: [1]
b: [3, 6, 4, 3, 9, 4]
[] [1] [3, 6, 4, 3, 9, 4]

middle: 3
s: []
e: [3, 3]
b: [6, 4, 9, 4]
[] [3, 3] [6, 4, 9, 4]

middle: 9
s: [6, 4, 4]
e: [9]
b: []
[6, 4, 4] [9] []

middle: 4
s: []
e: [4, 4]
b: [6]
[] [4, 4] [6]



[1, 3, 3, 4, 4, 6, 9]